### PR TITLE
chore: make logs in jbinit more noticeable

### PR DESCRIPTION
**Pull request by azaz0322**

### CODE REVIEW

**Comment by azaz0322** [comment]
wen

**Comment by kok3shidoll** [comment]
I really wonder if it is necessary

**Comment by azaz0322** [comment]
this would literally cut down support threads by a lot? there are so many people posting there daily just random screens of verbose output because they couldnt see the copying files bit be printed

**Comment by claration** [comment]
people can't really notice the ** so it may be necessary to see what even is going on

**Comment by azaz0322** [comment]
^

**Comment by ghost** [comment]
Yeah it can be useful. Maybe we should do the same for "jbinit DIED! cannot create fakefs over existing one" as well.

**Comment by azaz0322** [comment]
can get on that asap tomorrow (is 22:42 gmt rn so eep)

**Comment by kok3shidoll** [comment]
i mean, this method of copying uses the cp command to make a batch copy, there is not much difference in the ease of viewing the logs.

However, in such a case
```
echo '[*] copying /.ba'
cp -a /cores/fs/real/.ba /cores/fs/fake/
echo '[*] copying /.file'
cp -a /cores/fs/real/.file /cores/fs/fake/
echo '[*] copying /.mb'
cp -a /cores/fs/real/.mb /cores/fs/fake/
echo '[*] copying /Applications'
cp -a /cores/fs/real/Applications /cores/fs/fake/
...
```

**Comment by azaz0322** [comment]
at that point just use `cp -av [whatever]`

**Comment by kok3shidoll** [comment]
That's not good.
when try to run it, it shows too many logs and spends more time than necessary for logging.

**Comment by azaz0322** [comment]
image

**Comment by kok3shidoll** [comment]
Can you imagine how many files OS file system holds?
`cp -av` wastes more time than necessary because of the obviously too large amount of logs.

**Comment by azaz0322** [comment]
> Can you imagine how many files OS file system holds?
> 
> `cp -av` wastes more time than necessary because of the obviously too large amount of logs.

the original pr should be good enough anyway provided i make all the other messages more noticeable tomorrow

**Comment by kok3shidoll** [comment]
well, indeed, this would be good to have. but if it want to make the logs noticeable to read, it would be even better if could show the progress of the copy...

**Comment by azaz0322** [comment]
@0xallie done most of the more important logs, though some unimportant ones have been given the echo "==========================="; treatment, just less space taken up by screen. also did clear so it would be even more noticeable in comparison to other verbose text, however i am unclear on whether clear is included in the binpack and if it would actually clear the screen.

**Comment by ghost** [comment]
I'm not sure if it will actually work in jbinit, too lazy to check, but `printf '\033[2J'` should technically achieve the same thing even if there's no `clear` binary.

**Comment by azaz0322** [comment]
will commit

**Comment by itsnebulalol** [comment]
Please fix the conflicts. Why does it clear before saying done?

**Comment by azaz0322** [comment]
it is noticeable to the end user that the device has finished the process and will continue to reboot or whatever idk

**Comment by ghost** [comment]
It takes like 5 seconds to reboot so not sure if that's needed.

**Pull request merged**
